const courseSeeds = [
  {
    title: 'Learn Figma from Basics',
    category: 'Design',
    description:
      'Turn rough ideas into polished interfaces with a practical Figma workflow.',
    image: '/assets/courses/figma-basics.jpg',
    level: 'Beginner',
    durationMinutes: 95,
    lessons: 10,
    comments: 59,
    rating: 4.8,
    price: 19,
    creatorSlug: 'purepearl-studio',
  },
  {
    title: 'Design Systems in Figma',
    category: 'Design',
    description:
      'Build scalable libraries, tokens, and components for growing product teams.',
    image: '/assets/courses/figma-basics.jpg',
    level: 'Intermediate',
    durationMinutes: 180,
    lessons: 18,
    comments: 44,
    rating: 4.7,
    price: 35,
    creatorSlug: 'maya-khan',
  },
  {
    title: 'Product Thinking Essentials',
    category: 'Design',
    description:
      'Turn ambiguous product problems into clear opportunities and useful experiences.',
    image: '/assets/courses/digital-assets.jpg',
    level: 'Beginner',
    durationMinutes: 136,
    lessons: 14,
    comments: 38,
    rating: 4.6,
    price: 25,
    creatorSlug: 'maya-khan',
  },
  {
    title: 'Typography for Digital Products',
    category: 'Design',
    description:
      'Choose type with confidence and create hierarchy that makes products easier to use.',
    image: '/assets/courses/digital-assets.jpg',
    level: 'Beginner',
    durationMinutes: 120,
    lessons: 12,
    comments: 33,
    rating: 4.7,
    price: 25,
    creatorSlug: 'lina-park',
  },
  {
    title: 'Design Critique Workshop',
    category: 'Design',
    description:
      'Learn a clear critique process for giving and receiving useful design feedback.',
    image: '/assets/courses/digital-assets.jpg',
    level: 'Intermediate',
    durationMinutes: 150,
    lessons: 11,
    comments: 28,
    rating: 4.5,
    price: 29,
    creatorSlug: 'lina-park',
  },
  {
    title: 'Accessible React Interfaces',
    category: 'Development',
    description:
      'Build inclusive React interfaces with semantic HTML and keyboard support.',
    image: '/assets/courses/figma-basics.jpg',
    level: 'Intermediate',
    durationMinutes: 205,
    lessons: 20,
    comments: 86,
    rating: 4.9,
    price: 49,
    creatorSlug: 'nabil-ahmed',
  },
  {
    title: 'Modern CSS Layouts',
    category: 'Development',
    description:
      'Master responsive layout systems that stay elegant from phone to desktop.',
    image: '/assets/courses/figma-basics.jpg',
    level: 'Beginner',
    durationMinutes: 136,
    lessons: 15,
    comments: 63,
    rating: 4.7,
    price: 25,
    creatorSlug: 'nabil-ahmed',
  },
  {
    title: 'TypeScript for JavaScript Developers',
    category: 'Development',
    description:
      'Add reliable types to everyday JavaScript projects without slowing down.',
    image: '/assets/courses/figma-basics.jpg',
    level: 'Intermediate',
    durationMinutes: 180,
    lessons: 18,
    comments: 74,
    rating: 4.8,
    price: 35,
    creatorSlug: 'omar-hassan',
  },
  {
    title: 'Testing Frontend Applications',
    category: 'Development',
    description:
      'Create a practical testing strategy for components, flows, and regressions.',
    image: '/assets/courses/figma-basics.jpg',
    level: 'Intermediate',
    durationMinutes: 165,
    lessons: 16,
    comments: 42,
    rating: 4.6,
    price: 35,
    creatorSlug: 'omar-hassan',
  },
  {
    title: 'Git and GitHub in Practice',
    category: 'Development',
    description:
      'Use branches, pull requests, and collaboration habits that keep teams moving.',
    image: '/assets/courses/startup.jpg',
    level: 'Beginner',
    durationMinutes: 110,
    lessons: 12,
    comments: 51,
    rating: 4.7,
    price: 19,
    creatorSlug: 'omar-hassan',
  },
  {
    title: 'Python for Data Work',
    category: 'IT & Software',
    description:
      'Use Python fundamentals to clean, explore, and explain everyday datasets.',
    image: '/assets/courses/big-data.jpg',
    level: 'Beginner',
    durationMinutes: 210,
    lessons: 21,
    comments: 91,
    rating: 4.8,
    price: 49,
    creatorSlug: 'arif-rahman',
  },
  {
    title: 'SQL Queries for Analysts',
    category: 'IT & Software',
    description:
      'Write confident SQL queries for reporting, exploration, and business questions.',
    image: '/assets/courses/big-data.jpg',
    level: 'Beginner',
    durationMinutes: 145,
    lessons: 16,
    comments: 68,
    rating: 4.8,
    price: 35,
    creatorSlug: 'arif-rahman',
  },
  {
    title: 'Cloud Fundamentals',
    category: 'IT & Software',
    description:
      'Understand core cloud concepts, services, security, and deployment choices.',
    image: '/assets/courses/big-data.jpg',
    level: 'Beginner',
    durationMinutes: 170,
    lessons: 17,
    comments: 39,
    rating: 4.6,
    price: 35,
    creatorSlug: 'fatima-rahman',
  },
  {
    title: 'Cybersecurity Basics',
    category: 'IT & Software',
    description:
      'Build safer digital habits and understand the foundations of threat prevention.',
    image: '/assets/courses/big-data.jpg',
    level: 'Beginner',
    durationMinutes: 130,
    lessons: 13,
    comments: 57,
    rating: 4.7,
    price: 29,
    creatorSlug: 'fatima-rahman',
  },
  {
    title: 'Dashboard Storytelling',
    category: 'IT & Software',
    description:
      'Build dashboards that guide attention and help teams act on evidence.',
    image: '/assets/courses/big-data.jpg',
    level: 'Intermediate',
    durationMinutes: 120,
    lessons: 12,
    comments: 31,
    rating: 4.7,
    price: 25,
    creatorSlug: 'arif-rahman',
  },
  {
    title: 'Launch Your Creative Business',
    category: 'Business',
    description:
      'Shape a sustainable offer and find the people it is built to serve.',
    image: '/assets/courses/startup.jpg',
    level: 'Beginner',
    durationMinutes: 120,
    lessons: 12,
    comments: 58,
    rating: 4.8,
    price: 35,
    creatorSlug: 'aisha-noor',
  },
  {
    title: 'Systems for Freelancers',
    category: 'Business',
    description:
      'Create simple systems for managing projects, clients, and creative energy.',
    image: '/assets/courses/productivity.jpg',
    level: 'Intermediate',
    durationMinutes: 180,
    lessons: 17,
    comments: 34,
    rating: 4.6,
    price: 35,
    creatorSlug: 'elena-rodriguez',
  },
  {
    title: 'Finance for Small Businesses',
    category: 'Business',
    description:
      'Read your numbers, plan cash flow, and make calmer business decisions.',
    image: '/assets/courses/money-management.jpg',
    level: 'Beginner',
    durationMinutes: 140,
    lessons: 14,
    comments: 47,
    rating: 4.7,
    price: 29,
    creatorSlug: 'elena-rodriguez',
  },
  {
    title: 'Leading Remote Teams',
    category: 'Business',
    description:
      'Build clear rituals, trust, and accountability across distributed teams.',
    image: '/assets/courses/startup.jpg',
    level: 'Intermediate',
    durationMinutes: 155,
    lessons: 15,
    comments: 36,
    rating: 4.6,
    price: 35,
    creatorSlug: 'daniel-cho',
  },
  {
    title: 'Negotiation for Creatives',
    category: 'Business',
    description:
      'Prepare for better client conversations, scope decisions, and agreements.',
    image: '/assets/courses/startup.jpg',
    level: 'Beginner',
    durationMinutes: 100,
    lessons: 10,
    comments: 29,
    rating: 4.5,
    price: 19,
    creatorSlug: 'daniel-cho',
  },
  {
    title: 'Build a Personal Brand',
    category: 'Marketing',
    description:
      'Clarify your point of view and build a consistent presence people remember.',
    image: '/assets/courses/startup.jpg',
    level: 'Beginner',
    durationMinutes: 115,
    lessons: 11,
    comments: 52,
    rating: 4.7,
    price: 25,
    creatorSlug: 'sara-johnson',
  },
  {
    title: 'Campaigns That Convert',
    category: 'Marketing',
    description:
      'Connect audience insight to focused campaigns and measurable outcomes.',
    image: '/assets/courses/startup.jpg',
    level: 'Intermediate',
    durationMinutes: 180,
    lessons: 16,
    comments: 47,
    rating: 4.8,
    price: 35,
    creatorSlug: 'sara-johnson',
  },
  {
    title: 'Content Strategy Fundamentals',
    category: 'Marketing',
    description:
      'Plan useful content that supports your audience and your business goals.',
    image: '/assets/courses/productivity.jpg',
    level: 'Beginner',
    durationMinutes: 130,
    lessons: 13,
    comments: 61,
    rating: 4.6,
    price: 25,
    creatorSlug: 'sara-johnson',
  },
  {
    title: 'Email Marketing from Scratch',
    category: 'Marketing',
    description:
      'Create a practical email program with clear messages and healthy metrics.',
    image: '/assets/courses/productivity.jpg',
    level: 'Beginner',
    durationMinutes: 125,
    lessons: 12,
    comments: 45,
    rating: 4.7,
    price: 25,
    creatorSlug: 'mia-williams',
  },
  {
    title: 'Marketing Analytics Made Clear',
    category: 'Marketing',
    description:
      'Use simple measurement frameworks to understand what your marketing is doing.',
    image: '/assets/courses/big-data.jpg',
    level: 'Intermediate',
    durationMinutes: 160,
    lessons: 15,
    comments: 37,
    rating: 4.8,
    price: 35,
    creatorSlug: 'mia-williams',
  },
  {
    title: 'Portrait Lighting Workshop',
    category: 'Photography',
    description:
      'Shape expressive portraits with practical lighting setups and creative constraints.',
    image: '/assets/courses/digital-assets.jpg',
    level: 'Intermediate',
    durationMinutes: 205,
    lessons: 19,
    comments: 36,
    rating: 4.7,
    price: 49,
    creatorSlug: 'james-wilson',
  },
  {
    title: 'Photography with Intent',
    category: 'Photography',
    description:
      'Develop a confident visual voice through light, composition, and direction.',
    image: '/assets/courses/digital-assets.jpg',
    level: 'Beginner',
    durationMinutes: 136,
    lessons: 13,
    comments: 41,
    rating: 4.8,
    price: 25,
    creatorSlug: 'james-wilson',
  },
  {
    title: 'Street Photography Stories',
    category: 'Photography',
    description:
      'Find honest visual stories in everyday places without overcomplicating the shot.',
    image: '/assets/courses/digital-assets.jpg',
    level: 'Beginner',
    durationMinutes: 145,
    lessons: 14,
    comments: 32,
    rating: 4.6,
    price: 29,
    creatorSlug: 'noor-ahmed',
  },
  {
    title: 'Editing Photos in Lightroom',
    category: 'Photography',
    description:
      'Develop a repeatable editing workflow for natural, consistent photographs.',
    image: '/assets/courses/digital-assets.jpg',
    level: 'Intermediate',
    durationMinutes: 175,
    lessons: 17,
    comments: 54,
    rating: 4.8,
    price: 35,
    creatorSlug: 'noor-ahmed',
  },
  {
    title: 'Music Production for Beginners',
    category: 'Music',
    description:
      'Learn the creative and technical basics of making your first track.',
    image: '/assets/courses/startup.jpg',
    level: 'Beginner',
    durationMinutes: 190,
    lessons: 18,
    comments: 62,
    rating: 4.7,
    price: 35,
    creatorSlug: 'leo-martin',
  },
  {
    title: 'Songwriting with Structure',
    category: 'Music',
    description:
      'Turn fragments of melody and lyric into songs with shape and momentum.',
    image: '/assets/courses/startup.jpg',
    level: 'Beginner',
    durationMinutes: 125,
    lessons: 12,
    comments: 35,
    rating: 4.6,
    price: 25,
    creatorSlug: 'leo-martin',
  },
  {
    title: 'Mixing Vocals at Home',
    category: 'Music',
    description:
      'Record and mix clear, expressive vocals in a small home setup.',
    image: '/assets/courses/big-data.jpg',
    level: 'Intermediate',
    durationMinutes: 165,
    lessons: 15,
    comments: 28,
    rating: 4.8,
    price: 35,
    creatorSlug: 'leo-martin',
  },
  {
    title: 'Music Theory for Producers',
    category: 'Music',
    description:
      'Use harmony, rhythm, and arrangement ideas to make stronger production choices.',
    image: '/assets/courses/big-data.jpg',
    level: 'Beginner',
    durationMinutes: 150,
    lessons: 14,
    comments: 31,
    rating: 4.5,
    price: 29,
    creatorSlug: 'priya-shah',
  },
  {
    title: '2D Animation Fundamentals',
    category: 'Animation',
    description:
      'Bring drawings to life with timing, spacing, and expressive movement.',
    image: '/assets/courses/digital-assets.jpg',
    level: 'Beginner',
    durationMinutes: 210,
    lessons: 20,
    comments: 49,
    rating: 4.8,
    price: 49,
    creatorSlug: 'priya-shah',
  },
  {
    title: 'Motion Design for Social',
    category: 'Animation',
    description:
      'Create short, readable motion pieces designed for modern social feeds.',
    image: '/assets/courses/digital-assets.jpg',
    level: 'Intermediate',
    durationMinutes: 175,
    lessons: 16,
    comments: 42,
    rating: 4.7,
    price: 35,
    creatorSlug: 'priya-shah',
  },
  {
    title: 'Storyboarding for Short Films',
    category: 'Animation',
    description:
      'Plan shots, pacing, and visual beats before production begins.',
    image: '/assets/courses/startup.jpg',
    level: 'Beginner',
    durationMinutes: 140,
    lessons: 13,
    comments: 26,
    rating: 4.6,
    price: 29,
    creatorSlug: 'ethan-brooks',
  },
  {
    title: 'Character Animation Practice',
    category: 'Animation',
    description:
      'Develop believable character movement through focused animation exercises.',
    image: '/assets/courses/digital-assets.jpg',
    level: 'Intermediate',
    durationMinutes: 220,
    lessons: 21,
    comments: 33,
    rating: 4.9,
    price: 49,
    creatorSlug: 'ethan-brooks',
  },
  {
    title: 'Weeknight Cooking Foundations',
    category: 'Cooking',
    description:
      'Build a reliable kitchen routine with techniques for fast, balanced meals.',
    image: '/assets/courses/productivity.jpg',
    level: 'Beginner',
    durationMinutes: 110,
    lessons: 10,
    comments: 71,
    rating: 4.8,
    price: 19,
    creatorSlug: 'grace-lee',
  },
  {
    title: 'Bread Baking at Home',
    category: 'Cooking',
    description:
      'Understand dough, fermentation, and shaping for better homemade bread.',
    image: '/assets/courses/productivity.jpg',
    level: 'Beginner',
    durationMinutes: 165,
    lessons: 12,
    comments: 48,
    rating: 4.7,
    price: 29,
    creatorSlug: 'grace-lee',
  },
  {
    title: 'Plant-Based Comfort Food',
    category: 'Cooking',
    description:
      'Cook deeply satisfying plant-based meals with flexible everyday methods.',
    image: '/assets/courses/productivity.jpg',
    level: 'Intermediate',
    durationMinutes: 145,
    lessons: 13,
    comments: 39,
    rating: 4.6,
    price: 25,
    creatorSlug: 'grace-lee',
  },
  {
    title: 'Knife Skills and Kitchen Safety',
    category: 'Cooking',
    description:
      'Prepare ingredients faster and more safely with essential knife techniques.',
    image: '/assets/courses/money-management.jpg',
    level: 'Beginner',
    durationMinutes: 85,
    lessons: 8,
    comments: 55,
    rating: 4.9,
    price: 19,
    creatorSlug: 'hana-kim',
  },
] as const

export const courses = courseSeeds.map((course, index) => ({
  ...course,
  id: index + 1,
}))
export type Course = (typeof courses)[number]
