export const courses = [
  {
    id: 1,
    title: 'Learn Figma from Basic',
    image: '/assets/courses/figma-basics.jpg',
    category: 'UI/UX Design',
    description:
      'Learn the essentials of Figma and turn your ideas into polished, usable interfaces.',
    level: 'Beginner',
    durationMinutes: 95,
    lessons: 10,
    comments: 59,
    rating: 4.8,
    price: 19,
    creatorSlug: 'purepearl-studio',
  },
  {
    id: 2,
    title: 'Build Digital Assets',
    image: '/assets/courses/digital-assets.jpg',
    category: 'Drawing & Painting',
    description:
      'Create a versatile collection of digital assets for your next creative project.',
    level: 'Intermediate',
    durationMinutes: 205,
    lessons: 22,
    comments: 172,
    rating: 4.8,
    price: 35,
    creatorSlug: 'purepearl-studio',
  },
  {
    id: 3,
    title: 'Design Systems in Figma',
    image: '/assets/courses/figma-basics.jpg',
    category: 'UI/UX Design',
    description:
      'Create scalable libraries and thoughtful design tokens for growing product teams.',
    level: 'Intermediate',
    durationMinutes: 180,
    lessons: 18,
    comments: 44,
    rating: 4.7,
    price: 35,
    creatorSlug: 'maya-khan',
  },
  {
    id: 4,
    title: 'Product Thinking Essentials',
    image: '/assets/courses/digital-assets.jpg',
    category: 'UI/UX Design',
    description:
      'Turn ambiguous product problems into clear opportunities and useful experiences.',
    level: 'Beginner',
    durationMinutes: 136,
    lessons: 14,
    comments: 38,
    rating: 4.6,
    price: 25,
    creatorSlug: 'maya-khan',
  },
  {
    id: 5,
    title: 'The Power of Big Data',
    image: '/assets/courses/big-data.jpg',
    category: 'Data Science',
    description:
      'Find useful stories in data and make confident decisions with practical analysis.',
    level: 'Intermediate',
    durationMinutes: 205,
    lessons: 22,
    comments: 71,
    rating: 4.9,
    price: 49,
    creatorSlug: 'arif-rahman',
  },
  {
    id: 6,
    title: 'Dashboard Storytelling',
    image: '/assets/courses/big-data.jpg',
    category: 'Data Science',
    description:
      'Build dashboards that guide attention and help teams act on evidence.',
    level: 'Beginner',
    durationMinutes: 120,
    lessons: 12,
    comments: 31,
    rating: 4.7,
    price: 25,
    creatorSlug: 'arif-rahman',
  },
  {
    id: 7,
    title: 'Creative Branding Essentials',
    image: '/assets/courses/startup.jpg',
    category: 'Marketing',
    description:
      'Build a memorable brand foundation with clear positioning and visual direction.',
    level: 'Beginner',
    durationMinutes: 95,
    lessons: 10,
    comments: 52,
    rating: 4.6,
    price: 19,
    creatorSlug: 'sara-johnson',
  },
  {
    id: 8,
    title: 'Campaigns That Convert',
    image: '/assets/courses/startup.jpg',
    category: 'Marketing',
    description:
      'Plan focused campaigns that connect audience insight to measurable outcomes.',
    level: 'Intermediate',
    durationMinutes: 180,
    lessons: 16,
    comments: 47,
    rating: 4.8,
    price: 35,
    creatorSlug: 'sara-johnson',
  },
  {
    id: 9,
    title: 'Accessible React Interfaces',
    image: '/assets/courses/figma-basics.jpg',
    category: 'Web Development',
    description:
      'Build inclusive React interfaces with semantic HTML, keyboard support, and confidence.',
    level: 'Intermediate',
    durationMinutes: 205,
    lessons: 20,
    comments: 86,
    rating: 4.9,
    price: 49,
    creatorSlug: 'nabil-ahmed',
  },
  {
    id: 10,
    title: 'Modern CSS Layouts',
    image: '/assets/courses/figma-basics.jpg',
    category: 'Web Development',
    description:
      'Master responsive layout systems that stay elegant from phone to desktop.',
    level: 'Beginner',
    durationMinutes: 136,
    lessons: 15,
    comments: 63,
    rating: 4.7,
    price: 25,
    creatorSlug: 'nabil-ahmed',
  },
  {
    id: 11,
    title: 'Balancing Productivity and Self-Care',
    image: '/assets/courses/productivity.jpg',
    category: 'Productivity',
    description:
      'Build healthier routines that make room for focused work and personal wellbeing.',
    level: 'Beginner',
    durationMinutes: 95,
    lessons: 10,
    comments: 29,
    rating: 4.5,
    price: 19,
    creatorSlug: 'elena-rodriguez',
  },
  {
    id: 12,
    title: 'Systems for Freelancers',
    image: '/assets/courses/productivity.jpg',
    category: 'Freelance & Entrepreneurship',
    description:
      'Create simple systems for managing projects, clients, and your creative energy.',
    level: 'Intermediate',
    durationMinutes: 180,
    lessons: 17,
    comments: 34,
    rating: 4.6,
    price: 35,
    creatorSlug: 'elena-rodriguez',
  },
  {
    id: 13,
    title: 'Photography with Intent',
    image: '/assets/courses/photography.jpg',
    category: 'Photography',
    description:
      'Develop a confident visual voice through light, composition, and direction.',
    level: 'Beginner',
    durationMinutes: 136,
    lessons: 13,
    comments: 41,
    rating: 4.8,
    price: 25,
    creatorSlug: 'james-wilson',
  },
  {
    id: 14,
    title: 'Portrait Lighting Workshop',
    image: '/assets/courses/photography.jpg',
    category: 'Photography',
    description:
      'Shape expressive portraits with practical lighting setups and creative constraints.',
    level: 'Intermediate',
    durationMinutes: 205,
    lessons: 19,
    comments: 36,
    rating: 4.7,
    price: 49,
    creatorSlug: 'james-wilson',
  },
  {
    id: 15,
    title: 'Launch Your Creative Business',
    image: '/assets/courses/startup.jpg',
    category: 'Freelance & Entrepreneurship',
    description:
      'Shape a sustainable creative offer and find the people it is built to serve.',
    level: 'Beginner',
    durationMinutes: 120,
    lessons: 12,
    comments: 58,
    rating: 4.8,
    price: 35,
    creatorSlug: 'aisha-noor',
  },
  {
    id: 16,
    title: 'Community Building Basics',
    image: '/assets/courses/startup.jpg',
    category: 'Social Media',
    description:
      'Create a welcoming community rhythm that turns shared interests into belonging.',
    level: 'Beginner',
    durationMinutes: 95,
    lessons: 9,
    comments: 27,
    rating: 4.6,
    price: 19,
    creatorSlug: 'aisha-noor',
  },
] as const

export type Course = (typeof courses)[number]
