// Four course-specific modules per catalog entry, in the same order as courses.ts.
// Lesson titles, durations, summaries, and review references are derived from these outlines.
export const courseOutlines = [
  [
    'Figma workspace and frames',
    'Auto layout and components',
    'Styles and variants',
    'Responsive prototype',
  ],
  [
    'Digital asset planning',
    'Visual design principles',
    'Reusable asset production',
    'Portfolio and export',
  ],
  [
    'Framing product problems',
    'Customer needs and evidence',
    'Opportunity mapping',
    'Testing product ideas',
  ],
  [
    'Type scales and hierarchy',
    'Readable interface copy',
    'Pairing typefaces',
    'Responsive typography',
  ],
  [
    'Preparing a critique',
    'Giving actionable feedback',
    'Responding to feedback',
    'Running a design review',
  ],
  [
    'Semantic React markup',
    'Keyboard interactions',
    'Accessible forms',
    'Testing with assistive tools',
  ],
  ['Flexbox foundations', 'CSS grid layouts', 'Responsive breakpoints', 'Container-based layouts'],
  [
    'TypeScript fundamentals',
    'Union and object types',
    'Typing React components',
    'Safe API boundaries',
  ],
  ['Testing strategy', 'Component behavior tests', 'Mocking external data', 'Regression workflows'],
  [
    'Git history and branches',
    'Pull request workflow',
    'Resolving merge conflicts',
    'Review and release habits',
  ],
  ['Python data setup', 'Cleaning tabular data', 'Exploratory analysis', 'Reproducible notebooks'],
  [
    'Query fundamentals',
    'Joining related tables',
    'Grouping and aggregation',
    'Analyzing query results',
  ],
  ['Cloud service models', 'Compute and storage', 'Networking basics', 'Deploying a simple app'],
  [
    'Common digital threats',
    'Account protection',
    'Safe system practices',
    'Responding to incidents',
  ],
  [
    'Choosing useful metrics',
    'Selecting the right chart',
    'Dashboard hierarchy',
    'Explaining a data story',
  ],
  ['Finding a creative niche', 'Packaging an offer', 'Pricing services', 'Launching with clients'],
  [
    'Planning client projects',
    'Repeatable delivery steps',
    'Project handoffs',
    'Improving freelance systems',
  ],
  ['Business cash flow', 'Budgeting expenses', 'Pricing for margin', 'Forecasting decisions'],
  [
    'Remote team agreements',
    'Async communication',
    'Healthy meetings',
    'Feedback across time zones',
  ],
  [
    'Negotiation preparation',
    'Pricing and scope',
    'Handling objections',
    'Reaching a fair agreement',
  ],
  [
    'Audience and positioning',
    'Brand voice',
    'Portfolio storytelling',
    'Consistent online presence',
  ],
  ['Campaign objectives', 'Audience and message', 'Conversion paths', 'Campaign measurement'],
  ['Content audit', 'Editorial pillars', 'Publishing workflow', 'Measuring useful content'],
  [
    'Email audience segments',
    'Welcome sequence',
    'Writing useful emails',
    'Measuring email results',
  ],
  ['Marketing measurement', 'Campaign metrics', 'Attribution limits', 'Presenting insights'],
  ['Light direction', 'One-light portraits', 'Directing a subject', 'Editing portrait light'],
  ['Photographic intention', 'Composition choices', 'Building a series', 'Editing a photo story'],
  [
    'Observing street scenes',
    'Timing and framing',
    'Respectful street practice',
    'Sequencing a story',
  ],
  ['Lightroom workspace', 'Exposure and color', 'Local adjustments', 'Consistent export workflow'],
  ['Digital audio setup', 'Drum and bass ideas', 'Arranging a track', 'Finishing a first mix'],
  ['Song structure', 'Writing a hook', 'Verse and chorus', 'Revising a complete song'],
  ['Home vocal recording', 'Cleaning a vocal take', 'EQ and compression', 'Balancing a vocal mix'],
  ['Rhythm and intervals', 'Chords and progressions', 'Melodic tension', 'Writing with theory'],
  ['Animation timing', 'Spacing and weight', 'Bouncing movement', 'Polishing a short scene'],
  [
    'Motion hierarchy',
    'Animating text and shapes',
    'Social video pacing',
    'Exporting platform formats',
  ],
  ['Reading a short script', 'Shot composition', 'Visual continuity', 'Presenting a storyboard'],
  [
    'Expressive poses',
    'Anticipation and follow-through',
    'Walk cycle practice',
    'Character performance',
  ],
  [
    'Weeknight meal planning',
    'Preparation and timing',
    'Seasoning foundations',
    'Building a full dinner',
  ],
  [
    'Bread ingredients',
    'Mixing and kneading',
    'Fermentation and shaping',
    'Baking and troubleshooting',
  ],
  [
    'Plant-based pantry',
    'Flavor and texture',
    'Comfort food techniques',
    'Planning flexible meals',
  ],
  [
    'Knife and board safety',
    'Basic knife grips',
    'Consistent vegetable cuts',
    'Care and maintenance',
  ],
  [
    'Facial proportions',
    'Eyes and expressions',
    'Drawing varied faces',
    'Expression sheet practice',
  ],
  ['Color and value', 'Building palettes', 'Digital color mixing', 'Finishing a color study'],
  ['Selecting sketches', 'Scanning and cleanup', 'Digital layers', 'Preparing final artwork'],
  ['Light and shadow', 'Material surfaces', 'Brush and edge control', 'Painting a textured study'],
  [
    'Audience questions',
    'Useful social formats',
    'Writing stronger captions',
    'Planning a posting rhythm',
  ],
  ['Short-form story hooks', 'Planning a shot list', 'Editing for pace', 'Captions and publishing'],
  [
    'Community guidelines',
    'Helpful responses',
    'Handling difficult comments',
    'Measuring community health',
  ],
  [
    'Setting social goals',
    'Reading platform metrics',
    'Finding useful patterns',
    'Reporting next actions',
  ],
  ['User needs and flows', 'Wireframing interfaces', 'Usability principles', 'Testing a design'],
  [
    'Mobile navigation',
    'Touch-friendly controls',
    'Common app flows',
    'Adapting platform patterns',
  ],
  [
    'Planning a usability study',
    'Writing neutral tasks',
    'Running sessions',
    'Synthesizing findings',
  ],
  [
    'Campaign brief and audience',
    'Creative concept',
    'Visual direction',
    'Presenting campaign work',
  ],
  ['Brand message', 'Visual sequence', 'Cross-channel storytelling', 'Reviewing brand impact'],
  [
    'Defining the problem',
    'Writing a focused brief',
    'Aligning collaborators',
    'Reviewing creative work',
  ],
] as const
