export const creators = [
  {
    slug: 'purepearl-studio',
    name: 'PurePearl Studio',
    tagline: 'Passionate UI/UX, Web designer',
    bio: 'Welcome to the creative world of PurePearl Studio. Discover the passion, expertise, and inspiration behind every project, then explore practical courses that turn creative ideas into polished work.',
    avatar: '/assets/creators/purepearl-studio.png',
    followers: 12,
  },
  {
    slug: 'maya-khan',
    name: 'Maya Khan',
    tagline: 'Product designer & creative mentor',
    bio: 'Maya turns complex product ideas into simple, thoughtful experiences. Her courses make design systems and product thinking feel practical.',
    avatar: '/assets/learner-pink-background.png',
    followers: 124,
  },
  {
    slug: 'arif-rahman',
    name: 'Arif Rahman',
    tagline: 'Data analyst & visual storyteller',
    bio: 'Arif helps learners turn raw data into clear decisions through approachable analytics, dashboards, and real-world case studies.',
    avatar: '/assets/student-with-glasses.png',
    followers: 98,
  },
  {
    slug: 'sara-johnson',
    name: 'Sara Johnson',
    tagline: 'Growth marketer & brand strategist',
    bio: 'Sara shares practical frameworks for building memorable brands, stronger campaigns, and sustainable audience growth.',
    avatar: '/assets/learner-yellow-background.png',
    followers: 216,
  },
  {
    slug: 'nabil-ahmed',
    name: 'Nabil Ahmed',
    tagline: 'Frontend engineer & educator',
    bio: 'Nabil teaches modern frontend development with a focus on accessible interfaces, clean code, and confident problem-solving.',
    avatar: '/assets/student-with-hat.png',
    followers: 173,
  },
  {
    slug: 'elena-rodriguez',
    name: 'Elena Rodriguez',
    tagline: 'Business coach & systems builder',
    bio: 'Elena creates practical learning paths for freelancers and teams who want to work with greater clarity and momentum.',
    avatar: '/assets/student-pink-shirt.png',
    followers: 147,
  },
  {
    slug: 'james-wilson',
    name: 'James Wilson',
    tagline: 'Photography director & visual artist',
    bio: 'James helps creators develop a confident visual voice through lighting, composition, direction, and post-production.',
    avatar: '/assets/student-with-camera.png',
    followers: 89,
  },
  {
    slug: 'aisha-noor',
    name: 'Aisha Noor',
    tagline: 'Creative entrepreneur & community lead',
    bio: 'Aisha gives emerging creators the tools to shape sustainable creative careers and build communities around their work.',
    avatar: '/assets/learner-curly-hair.png',
    followers: 191,
  },
  {
    slug: 'lina-park',
    name: 'Lina Park',
    tagline: 'Type designer & design educator',
    bio: 'Lina helps product teams use typography and critique to make digital experiences clearer, calmer, and more human.',
    avatar: '/assets/learner-pink-background.png',
    followers: 138,
  },
  {
    slug: 'omar-hassan',
    name: 'Omar Hassan',
    tagline: 'Software engineer & open-source mentor',
    bio: 'Omar teaches practical engineering habits, from TypeScript and testing to the collaboration practices that make codebases healthier.',
    avatar: '/assets/student-with-hat.png',
    followers: 264,
  },
  {
    slug: 'fatima-rahman',
    name: 'Fatima Rahman',
    tagline: 'Cloud security specialist & teacher',
    bio: 'Fatima makes cloud infrastructure and security fundamentals approachable for curious builders and growing teams.',
    avatar: '/assets/student-with-glasses.png',
    followers: 187,
  },
  {
    slug: 'daniel-cho',
    name: 'Daniel Cho',
    tagline: 'Operations leader & team coach',
    bio: 'Daniel shares grounded systems for leading teams, negotiating clearly, and turning ambitious plans into steady progress.',
    avatar: '/assets/student-pink-shirt.png',
    followers: 154,
  },
  {
    slug: 'mia-williams',
    name: 'Mia Williams',
    tagline: 'Content strategist & growth advisor',
    bio: 'Mia helps small teams build focused content and marketing programs that are useful to audiences and measurable for businesses.',
    avatar: '/assets/learner-yellow-background.png',
    followers: 229,
  },
  {
    slug: 'noor-ahmed',
    name: 'Noor Ahmed',
    tagline: 'Documentary photographer & editor',
    bio: 'Noor teaches patient observation, intentional shooting, and thoughtful editing for photographers finding their visual voice.',
    avatar: '/assets/student-with-camera.png',
    followers: 116,
  },
  {
    slug: 'leo-martin',
    name: 'Leo Martin',
    tagline: 'Producer, songwriter & recording artist',
    bio: 'Leo breaks down the creative and technical decisions behind songwriting, home recording, and confident music production.',
    avatar: '/assets/learner-curly-hair.png',
    followers: 203,
  },
  {
    slug: 'priya-shah',
    name: 'Priya Shah',
    tagline: 'Animator & motion design director',
    bio: 'Priya teaches animation through clear exercises in timing, story, and movement that help ideas feel alive on screen.',
    avatar: '/assets/learner-blue-shirt.png',
    followers: 176,
  },
  {
    slug: 'ethan-brooks',
    name: 'Ethan Brooks',
    tagline: 'Character animator & storyboard artist',
    bio: 'Ethan helps emerging animators build expressive characters and plan visual stories with confidence.',
    avatar: '/assets/student-with-camera.png',
    followers: 142,
  },
  {
    slug: 'grace-lee',
    name: 'Grace Lee',
    tagline: 'Recipe developer & home cooking teacher',
    bio: 'Grace makes everyday cooking feel welcoming with flexible recipes, reliable techniques, and a little room for improvisation.',
    avatar: '/assets/learner-yellow-background.png',
    followers: 318,
  },
  {
    slug: 'hana-kim',
    name: 'Hana Kim',
    tagline: 'Chef and culinary fundamentals instructor',
    bio: 'Hana teaches the practical kitchen skills that make home cooking safer, faster, and more enjoyable.',
    avatar: '/assets/learner-pink-background.png',
    followers: 207,
  },
] as const

export type Creator = (typeof creators)[number]
