export const creators = [
  {
    slug: 'purepearl-studio',
    name: 'PurePearl Studio',
    tagline: 'Passionate UI/UX, Web designer',
    bio: 'Welcome to the creative world of PurePearl Studio. Discover the passion, expertise, and inspiration behind every project, then explore practical courses that turn creative ideas into polished work.',
    avatar: '/assets/creators/purepearl-studio.png',
    followers: 12,
  },
  {
    slug: 'maya-khan',
    name: 'Maya Khan',
    tagline: 'Product designer & creative mentor',
    bio: 'Maya turns complex product ideas into simple, thoughtful experiences. Her courses make design systems and product thinking feel practical.',
    avatar: '/assets/learner-pink-background.png',
    followers: 124,
  },
  {
    slug: 'arif-rahman',
    name: 'Arif Rahman',
    tagline: 'Data analyst & visual storyteller',
    bio: 'Arif helps learners turn raw data into clear decisions through approachable analytics, dashboards, and real-world case studies.',
    avatar: '/assets/student-with-glasses.png',
    followers: 98,
  },
  {
    slug: 'sara-johnson',
    name: 'Sara Johnson',
    tagline: 'Growth marketer & brand strategist',
    bio: 'Sara shares practical frameworks for building memorable brands, stronger campaigns, and sustainable audience growth.',
    avatar: '/assets/learner-yellow-background.png',
    followers: 216,
  },
  {
    slug: 'nabil-ahmed',
    name: 'Nabil Ahmed',
    tagline: 'Frontend engineer & educator',
    bio: 'Nabil teaches modern frontend development with a focus on accessible interfaces, clean code, and confident problem-solving.',
    avatar: '/assets/student-with-hat.png',
    followers: 173,
  },
  {
    slug: 'elena-rodriguez',
    name: 'Elena Rodriguez',
    tagline: 'Business coach & systems builder',
    bio: 'Elena creates practical learning paths for freelancers and teams who want to work with greater clarity and momentum.',
    avatar: '/assets/student-pink-shirt.png',
    followers: 147,
  },
  {
    slug: 'james-wilson',
    name: 'James Wilson',
    tagline: 'Photography director & visual artist',
    bio: 'James helps creators develop a confident visual voice through lighting, composition, direction, and post-production.',
    avatar: '/assets/student-with-camera.png',
    followers: 89,
  },
  {
    slug: 'aisha-noor',
    name: 'Aisha Noor',
    tagline: 'Creative entrepreneur & community lead',
    bio: 'Aisha gives emerging creators the tools to shape sustainable creative careers and build communities around their work.',
    avatar: '/assets/learner-curly-hair.png',
    followers: 191,
  },
] as const

export type Creator = (typeof creators)[number]
